channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - colorama
  - flake8
  - flit
  - ipython
  - isort
  - numpy
  - parse
  - pip
  - pytest
  - shapely
  - pip:
      - advent-of-code-data
      - black
      - pyplugs
