name    = "aoc"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gladvent     = ">= 1.0.1 and < 2.0.0"
birl         = ">= 1.7.1 and < 2.0.0"
birdie       = ">= 1.2.3 and < 2.0.0"
pprint       = ">= 1.0.3 and < 2.0.0"

[dev-dependencies]
argv         = ">= 1.0.2 and < 2.0.0"
gleeunit     = ">= 1.0.0 and < 2.0.0"
simplifile   = ">= 2.2.0 and < 3.0.0"
gleamy_bench = ">= 0.4.0 and < 1.0.0"

# Expectations
[gladvent.2015.1]
pt_1 = 232
pt_2 = 1_783

[gladvent.2015.2]
pt_1 = 1_598_415
pt_2 = 3_812_909

[gladvent.2017.1]
pt_1 = 1_141
pt_2 = 950

[gladvent.2018.1]
pt_1 = 531
pt_2 = 76_787

[gladvent.2018.2]
pt_1 = 4_693
pt_2 = "pebjqsalrdnckzfihvtxysomg"

[gladvent.2019.1]
pt_1 = 3_550_236
pt_2 = 5_322_455

[gladvent.2020.1]
pt_1 = 744_475
pt_2 = 70_276_940

[gladvent.2021.1]
pt_1 = 1_475
pt_2 = 1_516

[gladvent.2021.2]
pt_1 = 1_690_020
pt_2 = 1_408_487_760

[gladvent.2022.1]
pt_1 = 70_698
pt_2 = 206_643

[gladvent.2022.2]
pt_1 = 10_595
pt_2 = 9_541

[gladvent.2022.3]
pt_1 = 7_737
pt_2 = 2_697

[gladvent.2022.4]
pt_1 = 444
pt_2 = 801

[gladvent.2022.6]
pt_1 = 1_987
pt_2 = 3_059
